services:
    price-watch:
        image: ghcr.io/kimata/price-watch:latest@sha256:3f94e7c9ac0ccbb114c44c0047925a887a990a6244ea6a4eedbd49b69288b339
        tty: false
        stdin_open: true
        volumes:
            - ./config.yaml:/opt/price-watch/config.yaml:ro
            - ./target.yaml:/opt/price-watch/target.yaml:ro
            - ./data:/opt/price-watch/data
        ports:
            - "5000:5000"
