services:
    price-watch:
        image: ghcr.io/kimata/price-watch:latest@sha256:5cca3028eea3d180b4dcf0d31a6da0ef5a5d89a5a9b3edb9ab04f1688a390fdb
        tty: false
        stdin_open: true
        volumes:
            - ./config.yaml:/opt/price-watch/config.yaml:ro
            - ./target.yaml:/opt/price-watch/target.yaml:ro
            - ./data:/opt/price-watch/data
        ports:
            - "5000:5000"
