services:
    price-watch:
        image: ghcr.io/kimata/price-watch:latest@sha256:ded9b1e9e35640aba58406072d0f340098a8c0e44c1cea64551eaecfa3cd7b1b
        tty: false
        stdin_open: true
        volumes:
            - ./config.yaml:/opt/price-watch/config.yaml:ro
            - ./target.yaml:/opt/price-watch/target.yaml:ro
            - ./data:/opt/price-watch/data
        ports:
            - "5000:5000"
